title: Zenith Almador
description: Blog yang membahas seputar keamanan siber serta perlindungan dari ancaman aktor jahat.
show_downloads: false
hide_github: true

collections:
  blog:
    output: true
    permalink: /:title/

buttons:
  - text: ""
    href: "https://github.com/zenithnyan/zenithnyan.github.io/"

remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      hide_header: false

url: https://zenithnyan.github.io
baseurl: ""
